export const STORIES = [
  {
    id: 'morning',
    title: 'Утром без телефона',
    en_title: 'Morning Without the Phone',
    topic: '🌅 Daily Life',
    lines: [
      { speaker: 'А', ru: 'Слушай, ты реально каждое утро так рано встаёшь?', pr: 'SLU-shay, ty re-AL-no KAZH-do-ye UT-ro tak RA-no vsta-YOSH?', en: 'Hey, do you really wake up that early every morning?' },
      { speaker: 'Б', ru: 'Ну да. Сначала казалось — это пытка. А потом привык.', pr: 'nu da. sna-CHA-la ka-ZA-los — E-to PYT-ka. a po-TOM pri-VYK.', en: "Yeah. At first it felt like torture. Then I got used to it." },
      { speaker: 'А', ru: 'Блин. Я в семь уже не человек.', pr: 'blin. ya v sem uzhe ne che-lo-VEK.', en: "Damn. At seven I'm basically not human yet." },
      { speaker: 'Б', ru: 'Да ну. Это просто привычка. Тело само перестраивается.', pr: 'da nu. E-to PROS-to pri-VYCH-ka. TE-lo sa-MO pe-re-STRI-va-yet-sya.', en: 'Come on. It is just habit. The body adjusts on its own.' },
      { speaker: 'А', ru: 'А что делаешь прямо с утра?', pr: 'a shto DE-la-yesh PRYAM-o s UT-ra?', en: 'And what do you do first thing in the morning?' },
      { speaker: 'Б', ru: 'Стакан воды, тишина минут десять — и только потом телефон.', pr: 'sta-KAN vo-DY, ti-SHI-na mi-NUT DE-syat — i TOL-ko po-TOM te-le-FON.', en: 'Glass of water, ten minutes of silence — and only then the phone.' },
      { speaker: 'А', ru: 'Десять минут без телефона — это подвиг, честно.', pr: 'DE-syat mi-NUT bez te-le-FO-na — E-to POD-vig, CHEST-no.', en: "Ten minutes without the phone — honestly, that's heroic." },
      { speaker: 'Б', ru: 'Ха, ну вот в этом и весь смысл.', pr: 'kha, nu vot v E-tom i ves smysl.', en: 'Ha, well — that is exactly the point.' },
    ],
  },
  {
    id: 'burnout',
    title: 'Выгорание',
    en_title: 'Burnout',
    topic: '💆 Mental Health',
    lines: [
      { speaker: 'А', ru: 'Не понимаю, почему я такой уставший. Сплю же нормально.', pr: 'ne po-ni-MA-yu, po-che-MU ya ta-KOY us-TAV-shy. splyu zhe nor-MAL-no.', en: "I don't get why I'm so tired. I sleep fine." },
      { speaker: 'Б', ru: 'Слушай, а ты не думал, что это выгорание?', pr: 'SLU-shay, a ty ne DU-mal, shto E-to vy-go-RA-ni-ye?', en: 'Hey, have you thought that maybe this is burnout?' },
      { speaker: 'А', ru: 'Да ну, я не настолько занят.', pr: 'da nu, ya ne nas-TOL-ko ZA-nyat.', en: "Come on, I'm not that busy." },
      { speaker: 'Б', ru: 'Выгорание — это не про занятость. Это когда внутри пусто.', pr: 'vy-go-RA-ni-ye — E-to ne pro za-NYA-tost. E-to kog-DA vnuf-RI PUS-to.', en: "Burnout is not about being busy. It's when you feel empty inside." },
      { speaker: 'А', ru: 'Честно говоря... да. Прямо вот пусто.', pr: 'CHEST-no go-vo-RYA... da. PRYAM-o vot PUS-to.', en: 'Honestly... yes. Like, genuinely empty.' },
      { speaker: 'Б', ru: 'Тогда это оно. Надо остановиться, пока ещё есть силы.', pr: 'tog-DA E-to o-NO. NA-do os-ta-no-VIT-sya, po-KA ye-SHCHO yest SI-ly.', en: "Then that's it. You need to stop while you still have energy." },
      { speaker: 'А', ru: 'Легко говорить.', pr: 'lyek-KO go-vo-RIT.', en: 'Easy to say.' },
      { speaker: 'Б', ru: 'Начни с одного: один час — только для себя. Без задач.', pr: 'na-CHNI s od-NO-go: o-DIN chas — TOL-ko dlya se-BYA. bez za-DACH.', en: 'Start with one thing: one hour — just for yourself. No tasks.' },
    ],
  },
  {
    id: 'decision',
    title: 'Тяжёлый выбор',
    en_title: 'A Hard Choice',
    topic: '🔀 Life',
    lines: [
      { speaker: 'А', ru: 'Мне предложили работу мечты. Но надо переезжать.', pr: 'mne pred-lo-ZHI-li ra-BO-tu me-CHTYI. no NA-do pe-re-yez-ZHAT.', en: "I've been offered my dream job. But I'd have to move." },
      { speaker: 'Б', ru: 'Ничего себе. И что ты думаешь?', pr: 'ni-che-VO se-BYE. i shto ty DU-ma-yesh?', en: 'Wow. And what are you thinking?' },
      { speaker: 'А', ru: 'Не знаю. Страшно. Тут всё — семья, друзья.', pr: 'ne ZNA-yu. STRASH-no. tut vsyo — sem-YA, druz-YA.', en: "I don't know. It's scary. Everything is here — family, friends." },
      { speaker: 'Б', ru: 'А если не поедешь — потом пожалеешь?', pr: 'a YES-li ne po-YE-desh — po-TOM po-zha-LE-yesh?', en: "And if you don't go — will you regret it later?" },
      { speaker: 'А', ru: 'Вот именно в этом весь ужас.', pr: 'vot I-men-no v E-tom ves U-zhas.', en: "That's exactly the horror of it." },
      { speaker: 'Б', ru: 'Слушай, страх и интуиция — это разные вещи.', pr: 'SLU-shay, strakh i in-tu-I-tsi-ya — E-to RAZ-ny-ye VE-shchi.', en: 'Hey, fear and intuition — those are different things.' },
      { speaker: 'А', ru: 'А как различить?', pr: 'a kak raz-li-CHIT?', en: 'And how do you tell them apart?' },
      { speaker: 'Б', ru: 'Страх говорит «а вдруг». Интуиция говорит «знаю, но боюсь».', pr: 'strakh go-vo-RIT «a vdrug». in-tu-I-tsi-ya go-vo-RIT «ZNA-yu, no bo-YUS».', en: 'Fear says "what if." Intuition says "I know, but I\'m scared."' },
    ],
  },
  {
    id: 'impostor',
    title: 'Синдром самозванца',
    en_title: 'Impostor Syndrome',
    topic: '🧠 Self-Doubt',
    lines: [
      { speaker: 'А', ru: 'Типа, все вокруг такие уверенные, а я чувствую себя самозванцем.', pr: 'TI-pa, vse vok-RUG ta-KI-ye u-VE-ren-ny-ye, a ya CHUST-vu-yu se-BYA sa-mo-ZVAN-tsem.', en: "Like, everyone around seems so confident, and I feel like a fraud." },
      { speaker: 'Б', ru: 'Реально? Ты? Да ты столько всего сделал.', pr: 're-AL-no? ty? da ty STOL-ko vse-VO sde-LAL.', en: "Really? You? But you've done so much." },
      { speaker: 'А', ru: 'Ну и что. Внутри всё равно кажется, что я не тяну.', pr: 'nu i shto. vnuf-RI vsyo rav-NO KA-zhets-ya, shto ya ne tya-NU.', en: "So what. Inside it still feels like I can't handle it." },
      { speaker: 'Б', ru: 'Слушай, это называется синдром самозванца. У большинства умных людей так.', pr: 'SLU-shay, E-to na-zy-VA-yet-sya sin-DROM sa-mo-ZVAN-tsa. u bol-shin-STVA UM-nykh lyu-DEY tak.', en: "Hey, that's called impostor syndrome. Most smart people feel this way." },
      { speaker: 'А', ru: 'Серьёзно?', pr: 'ser-YO-zno?', en: 'Seriously?' },
      { speaker: 'Б', ru: 'Угу. Те, кто реально не тянет — они так не думают. Понял прикол?', pr: 'u-GU. te, kto re-AL-no ne TYA-net — o-NI tak ne DU-ma-yut. PO-nyal pri-KOL?', en: "Yep. People who genuinely can't handle it — they don't think this way. See the irony?" },
      { speaker: 'А', ru: 'Блин. Это... логично.', pr: 'blin. E-to... LO-gich-no.', en: 'Damn. That... makes sense.' },
      { speaker: 'Б', ru: 'Вот именно.', pr: 'vot I-men-no.', en: 'Exactly.' },
    ],
  },
  {
    id: 'phone',
    title: 'Телефон и голова',
    en_title: 'Phone and Your Head',
    topic: '📱 Digital Life',
    lines: [
      { speaker: 'А', ru: 'Короче, заметил — чем больше сижу в телефоне, тем тревожнее.', pr: 'KO-rot-che, za-ME-til — chem BOL-she si-ZHU v te-le-FO-ne, tem tre-VOZH-ne-ye.', en: "So basically, I noticed — the more I scroll, the more anxious I get." },
      { speaker: 'Б', ru: 'Да, это давно доказано. Соцсети — это дофаминовая ловушка.', pr: 'da, E-to dav-NO do-ka-ZA-no. sots-SE-ti — E-to do-fa-MI-no-va-ya lo-VUSH-ka.', en: "Yeah, that's been proven. Social media is a dopamine trap." },
      { speaker: 'А', ru: 'Ладно, но как не сидеть, когда всё там?', pr: 'LAD-no, no kak ne si-DET, kog-DA vsyo tam?', en: "Fine, but how do you not scroll when everything is there?" },
      { speaker: 'Б', ru: 'Я для себя сделал — первый и последний час без телефона.', pr: 'ya dlya se-BYA sde-LAL — PER-vy i pos-LED-ny chas bez te-le-FO-na.', en: "I made a rule for myself — first and last hour without the phone." },
      { speaker: 'А', ru: 'И что, реально помогает?', pr: 'i shto, re-AL-no po-mo-GA-yet?', en: 'And does it actually help?' },
      { speaker: 'Б', ru: 'Реально. Голова яснее, сплю лучше.', pr: 're-AL-no. go-lo-VA YAS-ne-ye, splyu LUCH-she.', en: 'For real. Head is clearer, I sleep better.' },
      { speaker: 'А', ru: 'Надо попробовать. Хотя, честно, звучит как пытка.', pr: 'NA-do po-PRO-bo-vat. kho-TYA, CHEST-no, zvu-CHIT kak PYT-ka.', en: 'Gotta try it. Though honestly it sounds like torture.' },
      { speaker: 'Б', ru: 'Первые три дня — пытка. Потом — кайф.', pr: 'PER-vy-ye tri dnya — PYT-ka. po-TOM — kayf.', en: 'First three days — torture. After that — bliss.' },
    ],
  },
  {
    id: 'meaning',
    title: 'А зачем вообще?',
    en_title: 'What Is the Point?',
    topic: '✨ Purpose',
    lines: [
      { speaker: 'А', ru: 'Слушай, ты когда-нибудь думаешь — а зачем всё это вообще?', pr: 'SLU-shay, ty kog-DA-ni-bud DU-ma-yesh — a za-CHEM vsyo E-to vob-SHCHE?', en: 'Hey, do you ever think — what is the point of all this anyway?' },
      { speaker: 'Б', ru: 'Ха. Ну, это уже философия начинается.', pr: 'kha. nu, E-to uzhe fi-lo-SO-fi-ya na-chi-NA-yet-sya.', en: "Ha. Well, that's where philosophy starts." },
      { speaker: 'А', ru: 'Нет, серьёзно. Вот работаю, устаю... а зачем?', pr: 'net, ser-YO-zno. vot ra-BO-ta-yu, us-ta-YU... a za-CHEM?', en: "No, seriously. I work, I get tired... but why?" },
      { speaker: 'Б', ru: 'Знаешь, я раньше тоже так думал. А потом понял — смысл не находят, его создают.', pr: 'ZNA-yesh, ya RAN-she TO-zhe tak DU-mal. a po-TOM PO-nyal — smysl ne na-KHO-dyat, ye-VO so-zda-YUT.', en: "You know, I used to think that too. Then I realised — meaning is not found, it is created." },
      { speaker: 'А', ru: 'Это как?', pr: 'E-to kak?', en: 'What do you mean?' },
      { speaker: 'Б', ru: 'Ну, ты сам решаешь, что важно. Не общество, не родители — ты.', pr: 'nu, ty sam re-SHA-yesh, shto VAZH-no. ne ob-SHCHE-stvo, ne ro-DI-te-li — ty.', en: "Like, you decide what matters. Not society, not your parents — you." },
      { speaker: 'А', ru: 'А если я пока не знаю, что важно?', pr: 'a YES-li ya po-KA ne ZNA-yu, shto VAZH-no?', en: "And what if I don't know yet what matters?" },
      { speaker: 'Б', ru: 'Вот это и есть начало. Незнание — это не проблема, это старт.', pr: 'vot E-to i yest na-CHA-lo. nez-NA-ni-ye — E-to ne prob-LE-ma, E-to start.', en: 'That is the beginning. Not knowing is not a problem — it is the starting point.' },
    ],
  },

  {
    id: 'consciousness',
    title: 'Загрузка сознания',
    en_title: 'Uploading Consciousness',
    topic: '🧠 Mind & Awareness',
    lines: [
      { speaker: 'А', ru: 'Слушай, ты когда-нибудь чувствовал, что реально просыпаешься? Не физически — вот здесь.', pr: 'SLU-shay, ty kog-DA-ni-bud chuvst-VO-val, shto re-AL-no pro-sy-PA-yesh-sya? ne fi-ZI-che-ski — vot zdes.', en: 'Hey, have you ever felt like you were really waking up? Not physically — like, in here.' },
      { speaker: 'Б', ru: 'Честно? Да. Был момент — всё как будто щёлкнуло. Раньше жил на автопилоте, блин.', pr: 'CHEST-no? da. byl mo-MENT — vsyo kak BUD-to SHCHOLK-nu-lo. RAN-she zhil na av-to-pi-LO-te, blin.', en: 'Honestly? Yeah. There was this moment — everything just clicked. Before that I was on autopilot, man.' },
      { speaker: 'А', ru: 'Вот именно! Я тоже. Короче, начал замечать всё по-другому. Цвета ярче, что ли.', pr: 'vot i-MEN-no! ya TO-zhe. KO-ro-che, na-CHAL za-me-CHAT vsyo po-dru-GO-mu. tsve-TA yar-CHE, shto li.', en: 'Exactly! Me too. I started noticing everything differently. Like colours felt brighter.' },
      { speaker: 'Б', ru: 'Это как загрузка новой версии себя. Ты уже не тот человек.', pr: 'E-to kak za-GRUZ-ka NO-voy VER-si-i se-BYA. ty uzhe ne tot che-lo-VEK.', en: "It's like uploading a new version of yourself. You're not the same person anymore." },
      { speaker: 'А', ru: 'Да, блин. И старые проблемы уже не кажутся такими большими. Смешно даже.', pr: 'da, blin. i STA-ry-ye prob-LE-my uzhe ne KA-zhut-sya ta-KI-mi bol-SHI-mi. smesh-NO da-ZHE.', en: "Yeah, man. And old problems don't seem that big anymore. It's actually funny." },
      { speaker: 'Б', ru: 'Ну и что ты делаешь по-другому теперь?', pr: 'nu i shto ty DE-la-yesh po-dru-GO-mu te-PER?', en: 'So what do you do differently now?' },
      { speaker: 'А', ru: 'Слушаю себя больше. Не других — себя. Внутренний голос — это реально мощно.', pr: 'SLU-sha-yu se-BYA BOLSH-e. ne dru-GIKH — se-BYA. vnut-REN-niy GO-los — E-to re-AL-no MOSHCH-no.', en: 'I listen to myself more. Not to others — to myself. The inner voice is seriously powerful.' },
      { speaker: 'Б', ru: 'Кайф. Это и есть сознание без границ. Самое классное путешествие — внутри.', pr: 'kayf. E-to i yest soz-NA-ni-ye bez gra-NITS. SA-mo-ye KLAS-sno-ye pu-te-SHEST-vi-ye — vnuf-RI.', en: "That's it. Consciousness without limits. The best journey is the one inside." },
    ],
  },

  {
    id: 'flow',
    title: 'В потоке',
    en_title: 'In the Flow',
    topic: '🎨 Creativity',
    lines: [
      { speaker: 'А', ru: 'Блин, сегодня работал четыре часа и даже не заметил. Просто улетел куда-то.', pr: 'blin, se-VOD-nya ra-BO-tal CHET-y-re cha-SA i DA-zhe ne za-ME-til. PROS-to u-le-TEL ku-DA-to.', en: "Man, I worked for four hours today and didn't even notice. I just took off somewhere." },
      { speaker: 'Б', ru: 'Поток, да? Это когда тебя нет — есть только то, что ты делаешь.', pr: 'po-TOK, da? E-to kog-DA te-BYA net — yest TOL-ko to, shto ty DE-la-yesh.', en: "Flow state, right? When you disappear — and there's only what you're doing." },
      { speaker: 'А', ru: 'Именно. Ни тревог, ни мыслей — просто чистое действие. Кайф нереальный.', pr: 'i-MEN-no. ni tre-VOG, ni MYS-ley — PROS-to CHIS-to-ye deystviye. kayf ne-re-AL-nyy.', en: 'Exactly. No anxiety, no thoughts — just pure action. Unreal feeling.' },
      { speaker: 'Б', ru: 'Слушай, и потом перечитываешь — и думаешь: это правда я сделал?', pr: 'SLU-shay, i po-TOM pe-re-CHI-ty-va-yesh — i DU-ma-yesh: E-to PRAV-da ya sde-LAL?', en: "And then you come back to it — and you think: did I really do this?" },
      { speaker: 'А', ru: 'Да, блин! Как будто через тебя что-то прошло, а не ты это создал.', pr: 'da, blin! kak BUD-to che-REZ te-BYA shto-TO prosh-LO, a ne ty E-to soz-DAL.', en: "Yes! Like something passed through you, not like you actually created it." },
      { speaker: 'Б', ru: 'Это и есть настоящее творчество. Когда эго уходит.', pr: 'E-to i yest nas-to-YASH-che-ye TVOR-che-stvo. kog-DA E-go u-KHO-dit.', en: "That's what real creativity is. When the ego steps aside." },
      { speaker: 'А', ru: 'Ну, а как войти в поток специально? Как его поймать?', pr: 'nu, a kak voy-TI v po-TOK spet-si-AL-no? kak ye-VO poy-MAT?', en: 'But how do you enter the flow intentionally? How do you catch it?' },
      { speaker: 'Б', ru: 'Короче, убираешь всё лишнее. Телефон, шум, планы. И просто начинаешь.', pr: 'KO-ro-che, u-bi-RA-yesh vsyo LISH-ne-ye. te-le-FON, shum, PLA-ny. i PROS-to na-chi-NA-yesh.', en: 'Basically, you remove everything extra. Phone, noise, plans. And you just start.' },
      { speaker: 'А', ru: 'Самое сложное — начать.', pr: 'SA-mo-ye SLOZH-no-ye — na-CHAT.', en: 'The hardest part is starting.' },
      { speaker: 'Б', ru: 'Именно. Потом само понесёт. Проверено.', pr: 'i-MEN-no. po-TOM sa-MO po-ne-SYOT. pro-ve-RE-no.', en: 'Exactly. After that it carries you. Tested and proven.' },
    ],
  },

  {
    id: 'inner_voice',
    title: 'Твой внутренний голос',
    en_title: 'Your Inner Voice',
    topic: '🎯 Intuition',
    lines: [
      { speaker: 'А', ru: 'Слушай, не могу решить. Голова говорит одно, а внутри — совсем другое.', pr: 'SLU-shay, ne mo-GU re-SHIT. go-lo-VA go-vo-RIT od-NO, a vnuf-RI — sov-SEM dru-GO-ye.', en: "Hey, I can't decide. My head says one thing, but inside it's completely different." },
      { speaker: 'Б', ru: 'И что внутри говорит?', pr: 'i shto vnuf-RI go-vo-RIT?', en: 'And what does the inside say?' },
      { speaker: 'А', ru: 'Нет. Чётко и ясно — нет. Но мозг подбирает миллион аргументов "за".', pr: 'net. CHOT-ko i YAS-no — net. no mozg pod-bi-RA-yet mil-LI-on ar-gu-MEN-tov "za".', en: 'No. Clear as day — no. But my brain keeps finding a million reasons "for."' },
      { speaker: 'Б', ru: 'Когда ты слушал интуицию — пожалел хоть раз?', pr: 'kog-DA ty SLU-shal in-tu-I-tsi-yu — po-zha-LEL khot raz?', en: 'When you listened to your intuition — did you ever regret it?' },
      { speaker: 'А', ru: 'Честно? Ни разу. Пожалел только тогда, когда не слушал.', pr: 'CHEST-no? ni RA-zu. po-zha-LEL TOL-ko to-GDA, kog-DA ne SLU-shal.', en: "Honestly? Not once. I only regretted it when I didn't listen." },
      { speaker: 'Б', ru: 'Вот именно. Внутренний голос — это не страх. Это знание.', pr: 'vot i-MEN-no. vnut-REN-niy GO-los — E-to ne strakh. E-to ZNA-ni-ye.', en: "Exactly. The inner voice isn't fear. It's knowledge." },
      { speaker: 'А', ru: 'Как их различить?', pr: 'kak ikh raz-li-CHIT?', en: 'How do you tell them apart?' },
      { speaker: 'Б', ru: 'Страх кричит. Интуиция говорит спокойно. Один раз — и всё.', pr: 'strakh kri-CHIT. in-tu-I-tsi-ya go-vo-RIT spo-KOY-no. o-DIN raz — i vsyo.', en: 'Fear screams. Intuition speaks quietly. Once — and that is it.' },
      { speaker: 'А', ru: 'Угу. Спокойно. Один раз. Ладно, я понял. Спасибо, братан.', pr: 'u-GU. spo-KOY-no. o-DIN raz. LAD-no, ya PO-nyal. spa-SI-bo, bra-TAN.', en: 'Right. Quietly. Once. Okay, I get it. Thanks, bro.' },
      { speaker: 'Б', ru: 'Ты уже знал ответ. Просто хотел, чтоб кто-то подтвердил.', pr: 'ty uzhe znal ot-VET. PROS-to kho-TEL, shtob kto-TO pod-tver-DIL.', en: 'You already knew the answer. You just wanted someone to confirm it.' },
    ],
  },

  {
    id: 'no_limits',
    title: 'Без границ',
    en_title: 'No Limits',
    topic: '🌌 Potential',
    lines: [
      { speaker: 'А', ru: 'Мне вчера дали задачу, которую я раньше бы точно отказался делать. Слишком сложно.', pr: 'mne vche-RA DA-li za-DA-chu, ko-TO-ru-yu ya RAN-she by TOCH-no ot-ka-ZAL-sya de-LAT. SLISH-kom SLOZH-no.', en: "Yesterday they gave me a task I would've definitely refused before. Too complicated." },
      { speaker: 'Б', ru: 'И что сделал?', pr: 'i shto sde-LAL?', en: 'And what did you do?' },
      { speaker: 'А', ru: 'Сделал. День занял, но сделал. И понял — "слишком сложно" — это не реальная вещь.', pr: 'sde-LAL. den za-NYAL, no sde-LAL. i PO-nyal — "SLISH-kom SLOZH-no" — E-to ne re-AL-na-ya veshch.', en: 'I did it. It took a day, but I did it. And I realised — "too complicated" — that\'s not even a real thing.' },
      { speaker: 'Б', ru: 'Это ограничение существует только в голове.', pr: 'E-to og-ra-ni-CHE-ni-ye su-shche-STVU-yet TOL-ko v go-lo-VE.', en: 'That limit only exists in your head.' },
      { speaker: 'А', ru: 'Именно, блин. Мозг экономит энергию. Видит что-то большое — сразу говорит "нет".', pr: 'i-MEN-no, blin. mozg e-ko-NO-mit e-NER-gi-yu. VI-dit shto-TO bol-SHO-ye — SRA-zu go-vo-RIT "net".', en: 'Exactly, man. The brain conserves energy. It sees something big — immediately says "no."' },
      { speaker: 'Б', ru: 'А ты его переключил. Просто начал — шаг за шагом.', pr: 'a ty ye-VO pe-re-KLYUCH-il. PROS-to na-CHAL — shag za SHA-gom.', en: 'And you overrode it. Just started — step by step.' },
      { speaker: 'А', ru: 'Да. И теперь следующая задача уже не кажется страшной. Интересно даже.', pr: 'da. i te-PER SLE-du-yu-shcha-ya za-DA-cha uzhe ne KA-zhit-sya strash-NOY. in-te-RES-no DA-zhe.', en: "Yeah. And now the next task doesn't seem scary. It's actually interesting." },
      { speaker: 'Б', ru: 'Вот так и работает эволюция. По одному барьеру за раз. Без границ.', pr: 'vot tak i ra-BO-ta-yet e-vo-LYU-tsi-ya. po od-no-MU bar-YE-ru za raz. bez gra-NITS.', en: "That's how evolution works. One barrier at a time. No limits." },
    ],
  },

  {
    id: 'frequency',
    title: 'Высокая частота',
    en_title: 'High Frequency',
    topic: '⚡ Energy',
    lines: [
      { speaker: 'А', ru: 'Ты заметил — есть дни, когда всё идёт легко? Всё совпадает как будто.', pr: 'ty za-ME-til — yest dni, kog-DA vsyo i-DYOT leg-KO? vsyo sov-pa-DA-yet kak BUD-to.', en: 'Have you noticed — there are days when everything flows easily? Like everything aligns.' },
      { speaker: 'Б', ru: 'Угу. А есть дни — хоть убейся, ничего не клеится.', pr: 'u-GU. a yest dni — khot u-BEY-sya, ni-che-GO ne KLEI-tsya.', en: "Yeah. And there are days — no matter what you do, nothing sticks." },
      { speaker: 'А', ru: 'Я думаю, это про частоту. На каком уровне ты вибрируешь.', pr: 'ya DU-ma-yu, E-to pro CHAS-to-tu. na ka-KOM u-ROV-ne ty vi-bri-RU-yesh.', en: "I think it's about frequency. What level you're vibrating at." },
      { speaker: 'Б', ru: 'Звучит как эзотерика, блин.', pr: 'zvu-CHIT kak e-zo-TE-ri-ka, blin.', en: 'That sounds like mysticism, man.' },
      { speaker: 'А', ru: 'Ну, может. Но объясни — почему с одними людьми энергия прёт, а с другими сдувает?', pr: 'nu, MO-zhet. no ob-yaz-NI — po-che-MU s od-NI-mi LYUD-mi e-NER-gi-ya pryet, a s dru-GI-mi sdu-VA-yet?', en: "Well, maybe. But explain — why does energy surge around some people and drain with others?" },
      { speaker: 'Б', ru: 'Да ну, это правда. Есть люди — час поговорил и как зарядился.', pr: 'da nu, E-to PRAV-da. yest LYU-di — chas po-go-vo-RIL i kak za-rya-DIL-sya.', en: "You're right, actually. Some people — you talk an hour and feel charged up." },
      { speaker: 'А', ru: 'Так это и есть частота. Чем выше ты сам — тем больше притягиваешь такого же.', pr: 'tak E-to i yest CHAS-to-ta. chem VYSH-e ty sam — tem BOLSH-e pri-TYA-gi-va-yesh ta-KO-go zhe.', en: "That's exactly what frequency is. The higher you are — the more you attract the same." },
      { speaker: 'Б', ru: 'И как поднять свою частоту?', pr: 'i kak pod-NYAT svo-YU CHAS-to-tu?', en: 'And how do you raise your own frequency?' },
      { speaker: 'А', ru: 'Делай то, что реально кайфово. Не по обязанности — по зову.', pr: 'de-LAY to, shto re-AL-no KAY-fo-vo. ne po o-bya-ZAN-nos-ti — po ZO-vu.', en: "Do what genuinely lights you up. Not out of obligation — out of calling." },
      { speaker: 'Б', ru: 'Короче, живи как будто ты уже там, где хочешь быть.', pr: 'KO-ro-che, ZHI-vi kak BUD-to ty uzhe tam, gde KHO-chesh byt.', en: 'Basically, live as if you are already where you want to be.' },
    ],
  },

  {
    id: 'dream_reality',
    title: 'Снится или нет?',
    en_title: 'Dream or Reality?',
    topic: '🌙 Consciousness',
    lines: [
      { speaker: 'А', ru: 'У меня вчера был сон такой реальный — до сих пор помню каждую деталь.', pr: 'u me-NYA vche-RA byl son ta-KOY re-AL-nyy — do sikh por POM-nyu KAZH-du-yu de-TAL.', en: 'I had this dream yesterday so real — I still remember every detail.' },
      { speaker: 'Б', ru: 'Это люцидный сон? Где ты понимаешь, что спишь?', pr: 'E-to LYU-tsid-nyy son? gde ty po-ni-MA-yesh, shto spish?', en: 'Was it a lucid dream? Where you realize you are sleeping?' },
      { speaker: 'А', ru: 'Нет, хуже. Не понимал. Казалось — это жизнь настоящая. Проснулся — и как разочаровался.', pr: 'net, KHUZH-e. ne po-ni-MAL. ka-ZA-los — E-to zhizn nas-to-YASH-cha-ya. pros-NUL-sya — i kak ra-zo-cha-ro-VAL-sya.', en: 'No, worse. I had no idea. It felt like real life. Then I woke up — and I was genuinely disappointed.' },
      { speaker: 'Б', ru: 'Блин, это значит мозг создал целый мир. Со своей физикой, людьми, логикой.', pr: 'blin, E-to ZNA-chit mozg soz-DAL TSE-lyy mir. so svo-YEY fi-ZI-key, LYUD-mi, LO-gi-key.', en: "Man, that means your brain created a whole world. With its own physics, people, logic." },
      { speaker: 'А', ru: 'И ты там живёшь как настоящий. Полностью веришь.', pr: 'i ty tam zhi-VYOSH kak nas-to-YASH-chiy. POL-nos-tyu VE-rish.', en: 'And you live there as if it is real. You fully believe it.' },
      { speaker: 'Б', ru: 'А вдруг и здесь так же? Как ты знаешь, что это реальность?', pr: 'a vdrug i zdes tak ZHE? kak ty ZNA-yesh, shto E-to re-AL-nost?', en: 'What if it is the same here? How do you even know this is reality?' },
      { speaker: 'А', ru: 'Да ну, не начинай. Голова взорвётся.', pr: 'da nu, ne na-chi-NAY. go-lo-VA vzor-VYOT-sya.', en: "Come on, don't start. My brain will explode." },
      { speaker: 'Б', ru: 'Сознание — это и есть реальность. Аетермайнд, понимаешь?', pr: 'soz-NA-ni-ye — E-to i yest re-AL-nost. A-e-ter-MAYND, po-ni-MA-yesh?', en: 'Consciousness — that IS reality. Aethermind, you know?' },
      { speaker: 'А', ru: 'Ладно, философ. Главное — где лучше, там и живи. Хоть во сне.', pr: 'LAD-no, fi-lo-SOF. GLAV-no-ye — gde LUCH-she, tam i ZHI-vi. khot vo sne.', en: 'Okay, philosopher. The point is — wherever it is better, live there. Even in dreams.' },
      { speaker: 'Б', ru: 'Кайф. Это мудро, блин.', pr: 'kayf. E-to MUD-ro, blin.', en: 'That is actually wise, man.' },
    ],
  },

  {
    id: 'detox',
    title: 'Цифровой отдых',
    en_title: 'Digital Detox',
    topic: '📵 Digital Life',
    lines: [
      { speaker: 'А', ru: 'Я вчера телефон выключил на весь день. Впервые за не знаю сколько лет.', pr: 'ya vche-RA te-le-FON vyk-LYU-chil na ves den. vper-VYE za ne ZNA-yu SKOL-ko let.', en: "I turned my phone off for the whole day yesterday. For the first time in I don't know how many years." },
      { speaker: 'Б', ru: 'И что? Пережил?', pr: 'i shto? pe-re-ZHIL?', en: 'And? Did you survive?' },
      { speaker: 'А', ru: 'Первые два часа — паника. Руки сами тянулись. Рефлекс уже.', pr: 'PER-vy-ye dva cha-SA — PA-ni-ka. RU-ki SA-mi TYA-nu-lis. re-FLEKS uzhe.', en: 'The first two hours — panic. My hands kept reaching for it on their own. It is a reflex now.' },
      { speaker: 'Б', ru: 'А потом?', pr: 'a po-TOM?', en: 'And then?' },
      { speaker: 'А', ru: 'А потом... тишина. Реальная. Я даже забыл, как это — просто сидеть.', pr: 'a po-TOM... ti-SHI-na. re-AL-na-ya. ya DA-zhe za-BYL, kak E-to — PROS-to si-DET.', en: "And then... silence. Real silence. I'd even forgotten what it's like to just sit." },
      { speaker: 'Б', ru: 'Блин, это страшно — что мы забыли.', pr: 'blin, E-to STRASH-no — shto my za-BY-li.', en: "Man, that's scary — that we forgot." },
      { speaker: 'А', ru: 'И мысли пошли другие. Не тревожные — творческие. Вспомнил, чего хочу вообще.', pr: 'i MYS-li posh-LI dru-GI-ye. ne tre-VOZH-ny-ye — TVOR-che-ski-ye. vspo-MIL, che-GO kho-CHU vo-ob-SHCHE.', en: 'And different thoughts started coming. Not anxious ones — creative ones. I remembered what I actually want.' },
      { speaker: 'Б', ru: 'То есть шум заглушает тебя самого.', pr: 'to yest shum zag-lu-SHA-yet te-BYA sa-MO-go.', en: 'So the noise drowns out you yourself.' },
      { speaker: 'А', ru: 'Когда всё замолкает — слышишь себя. Это и есть настройка.', pr: 'kog-DA vsyo za-MOL-ka-yet — SLY-shish se-BYA. E-to i yest nas-TROYK-a.', en: 'When everything goes quiet — you hear yourself. That is the tuning.' },
      { speaker: 'Б', ru: 'Короче, тишина — это не скука. Это обновление системы.', pr: 'KO-ro-che, ti-SHI-na — E-to ne SKU-ka. E-to ob-nov-LEN-ni-ye sis-TE-my.', en: "Basically, silence isn't boredom. It's a system update." },
    ],
  },

  {
    id: 'evolution',
    title: 'Эволюция',
    en_title: 'Evolution',
    topic: '🌱 Growth',
    lines: [
      { speaker: 'А', ru: 'Нашёл старые переписки. Три года назад. Читаю — это вообще кто?', pr: 'na-SHYOL STA-ry-ye pe-re-PIS-ki. tri GO-da na-ZAD. chi-TA-yu — E-to vo-ob-SHCHE kto?', en: 'I found old messages. Three years ago. I am reading them — who even is this?' },
      { speaker: 'Б', ru: 'Хах. Это хороший знак, если так думаешь.', pr: 'khakh. E-to kho-RO-shiy znak, YES-li tak DU-ma-yesh.', en: 'Hah. That is a good sign, if you think that.' },
      { speaker: 'А', ru: 'Да? Почему?', pr: 'da? po-che-MU?', en: 'Yeah? Why?' },
      { speaker: 'Б', ru: 'Потому что ты вырос. Прошлый ты бы нынешнего не понял.', pr: 'po-to-MU shto ty vy-ROS. PROSH-lyy ty by NY-nesh-ne-go ne po-NYAL.', en: "Because you grew. Your past self wouldn't understand your current self." },
      { speaker: 'А', ru: 'Блин, это и страшно, и кайфово одновременно. Как другой человек.', pr: 'blin, E-to i STRASH-no, i KAY-fo-vo od-no-vre-MEN-no. kak dru-GOY che-lo-VEK.', en: "Man, that's both scary and amazing at the same time. Like a different person." },
      { speaker: 'Б', ru: 'А чего ты три года назад боялся — сейчас боишься?', pr: 'a che-GO ty tri GO-da na-ZAD bo-YAL-sya — sey-CHAS bo-ISH-sya?', en: 'And what you were afraid of three years ago — are you still afraid of it?' },
      { speaker: 'А', ru: 'Нет. Вообще нет. Смешно даже вспомнить.', pr: 'net. vo-ob-SHCHE net. smesh-NO DA-zhe vspo-MNIT.', en: "No. Not at all. It's funny to even remember." },
      { speaker: 'Б', ru: 'Значит через три года нынешние страхи тоже будут смешными.', pr: 'ZNA-chit che-REZ tri GO-da NY-nesh-ni-ye STRA-khi TO-zhe bu-DUT smesh-NY-mi.', en: 'Meaning in three years, your current fears will also seem funny.' },
      { speaker: 'А', ru: 'Если так думать — они уже не такие страшные. Всё меняется.', pr: 'YES-li tak du-MAT — o-NI uzhe ne ta-KI-ye strash-NY-ye. vsyo me-NYA-yet-sya.', en: 'If you think like that — they are not so scary already. Everything changes.' },
      { speaker: 'Б', ru: 'Эволюция — это не цель. Это постоянный процесс. Ты всегда в пути.', pr: 'e-vo-LYU-tsi-ya — E-to ne tsel. E-to pos-to-YAN-nyy pro-TSESS. ty vseg-DA v pu-TI.', en: "Evolution isn't a destination. It's a constant process. You are always on the way." },
    ],
  },

  {
    id: 'creative_block',
    title: 'Творческий кризис',
    en_title: 'Creative Block',
    topic: '🎭 Art & Expression',
    lines: [
      { speaker: 'А', ru: 'Уже неделю ничего не делаю. Сижу — пусто. Ни одной мысли.', pr: 'uzhe ne-DE-lyu ni-che-GO ne de-LA-yu. SIZ-hu — PUS-to. ni od-NOY MYS-li.', en: "Haven't done anything for a week. I sit down — empty. Not a single thought." },
      { speaker: 'Б', ru: 'Блин. Тяжело. Кризис?', pr: 'blin. TYAZH-e-lo. KRI-zis?', en: 'Man. That is rough. A block?' },
      { speaker: 'А', ru: 'Хуже. Раньше хоть что-то приходило. Сейчас — как выключили.', pr: 'KHUZH-e. RAN-she khot shto-TO pri-kho-DI-lo. sey-CHAS — kak vyk-LYU-chi-li.', en: 'Worse. Before, at least something would come. Now — like someone switched me off.' },
      { speaker: 'Б', ru: 'Слушай, а ты давно отдыхал по-настоящему?', pr: 'SLU-shay, a ty dav-NO ot-dy-KHAL po-nas-to-YASH-che-mu?', en: 'Hey, when did you last rest for real?' },
      { speaker: 'А', ru: 'Ну... не помню. Всё время что-то делаю.', pr: 'nu... ne POM-nyu. vsyo VRE-mya shto-TO de-LA-yu.', en: "Well... I don't remember. I'm always doing something." },
      { speaker: 'Б', ru: 'Вот и ответ, братан. Пустота — это не конец. Это организм говорит: стоп.', pr: 'vot i ot-VET, bra-TAN. pus-to-TA — E-to ne ko-NETS. E-to or-ga-NIZM go-vo-RIT: stop.', en: "There is your answer, bro. The emptiness is not the end. Your body is saying: stop." },
      { speaker: 'А', ru: 'Но если не делаю — кажется, теряю навык. Деградирую.', pr: 'no YES-li ne de-LA-yu — KA-zhit-sya, te-RYA-yu NA-vyk. deg-ra-di-RU-yu.', en: "But if I'm not doing anything — it feels like I'm losing my skill. Regressing." },
      { speaker: 'Б', ru: 'Неа. Творчество — как батарейка. Если не заряжать — разрядится. Живи сначала.', pr: 'ne-A. TVOR-chest-vo — kak ba-ta-REYK-a. YES-li ne za-rya-ZHAT — raz-rya-DIT-sya. ZHI-vi sna-CHA-la.', en: "Nope. Creativity is like a battery. If you don't charge it — it dies. Live first." },
      { speaker: 'А', ru: 'Просто жить. Без задач.', pr: 'PROS-to zhit. bez za-DACH.', en: 'Just live. Without tasks.' },
      { speaker: 'Б', ru: 'Именно. Напишешь потом. Когда будет что сказать — скажешь.', pr: 'i-MEN-no. na-PI-shesh po-TOM. kog-DA bu-DET shto ska-ZAT — SKA-zhesh.', en: "Exactly. You will create later. When you have something to say — you will say it." },
    ],
  },

  {
    id: 'parallel_paths',
    title: 'Параллельные пути',
    en_title: 'Parallel Paths',
    topic: '🔀 Choices',
    lines: [
      { speaker: 'А', ru: 'Иногда думаю — а что если бы я выбрал по-другому? Пять лет назад.', pr: 'i-NOG-da DU-ma-yu — a shto YES-li by ya VY-bral po-dru-GO-mu? pyat let na-ZAD.', en: 'Sometimes I think — what if I had chosen differently? Five years ago.' },
      { speaker: 'Б', ru: 'И что бы было?', pr: 'i shto by BY-lo?', en: 'And what would have happened?' },
      { speaker: 'А', ru: 'Не знаю. Может лучше. Может хуже. Другая жизнь, другой я.', pr: 'ne ZNA-yu. MO-zhet LUCH-she. MO-zhet KHUZH-e. dru-GA-ya zhizn, dru-GOY ya.', en: "I don't know. Maybe better. Maybe worse. A different life, a different me." },
      { speaker: 'Б', ru: 'Но ты бы тогда не был здесь. С тем, что у тебя есть сейчас.', pr: 'no ty by tog-DA ne byl zdes. s tem, shto u te-BYA yest sey-CHAS.', en: "But you would not be here then. With what you have now." },
      { speaker: 'А', ru: 'Сейчас есть вещи, которые я не отдам ни за что.', pr: 'sey-CHAS yest VESH-chi, ko-TO-ry-ye ya ne ot-DAM ni za shto.', en: "There are things now I would not give up for anything." },
      { speaker: 'Б', ru: 'Значит каждый выбор привёл именно сюда. Не случайно.', pr: 'ZNA-chit KAZH-dyy VY-bor pri-VYOL i-MEN-no syu-DA. ne slu-CHAY-no.', en: 'So every choice led exactly here. Not by accident.' },
      { speaker: 'А', ru: 'Это красиво. Но страшно — значит сейчас я тоже что-то выбираю. Что изменит всё.', pr: 'E-to kra-SI-vo. no STRASH-no — ZNA-chit sey-CHAS ya TO-zhe shto-TO vy-bi-RA-yu. shto iz-me-NIT vsyo.', en: "That is beautiful. But scary — meaning right now I am also choosing something. That will change everything." },
      { speaker: 'Б', ru: 'Постоянно. Каждый день. Это и есть жизнь.', pr: 'pos-to-YAN-no. KAZH-dyy den. E-to i yest zhizn.', en: 'Constantly. Every day. That is what life is.' },
      { speaker: 'А', ru: 'Тогда надо выбирать осознанно. А не на автомате.', pr: 'tog-DA NA-do vy-bi-RAT o-soz-NAN-no. a ne na av-to-MA-te.', en: 'Then you have to choose consciously. Not on autopilot.' },
      { speaker: 'Б', ru: 'Ты уже это делаешь. Раз задаёшь такие вопросы.', pr: 'ty uzhe E-to DE-la-yesh. raz za-da-YOSH ta-KI-ye vop-RO-sy.', en: 'You are already doing it. The fact that you ask these questions.' },
    ],
  },
];
