export const STORIES = [
  {
    id: 'morning',
    title: 'Утренняя рутина',
    en_title: 'Morning Routine',
    topic: '🌅 Mindfulness',
    lines: [
      { speaker: 'А', ru: 'Как ты начинаешь каждое утро?', pr: 'kak ty na-chi-NA-yesh KAZH-do-ye UT-ro?', en: 'How do you start every morning?' },
      { speaker: 'Б', ru: 'Я встаю рано и сразу медитирую.', pr: 'ya vsta-YU RA-no i sra-ZU me-di-TI-ru-yu.', en: 'I wake up early and meditate right away.' },
      { speaker: 'А', ru: 'Это тяжело — вставать так рано.', pr: 'E-to tyazh-E-lo — vsta-VAT tak RA-no.', en: "That's hard — waking up so early." },
      { speaker: 'Б', ru: 'Первые три дня трудно, потом тело привыкает.', pr: 'PER-vy-ye tri dnya TRUD-no, po-TOM TE-lo pri-vy-KA-yet.', en: 'The first three days are tough, then the body adapts.' },
      { speaker: 'А', ru: 'Что ты чувствуешь после медитации?', pr: 'shto ty CHUST-vu-yesh POS-le me-di-TA-tsi-i?', en: 'How do you feel after meditation?' },
      { speaker: 'Б', ru: 'Спокойствие. Как будто мозг перезагрузился.', pr: 'spo-KOY-stvi-ye. kak BUD-to mozg pe-re-za-gru-ZIL-sya.', en: 'Calm. As if the brain rebooted itself.' },
    ],
  },
  {
    id: 'goals',
    title: 'Цели и намерения',
    en_title: 'Goals & Intentions',
    topic: '🎯 Growth',
    lines: [
      { speaker: 'А', ru: 'Какая у тебя главная цель на этот год?', pr: 'ka-KA-ya u te-BYA GLAV-na-ya tsel na E-tot god?', en: 'What is your main goal for this year?' },
      { speaker: 'Б', ru: 'Я хочу стать лучшей версией себя.', pr: 'ya kho-CHU stat LUCH-shey VER-si-yey se-BYAH.', en: 'I want to become the best version of myself.' },
      { speaker: 'А', ru: 'Это звучит абстрактно. Как ты это измеришь?', pr: 'E-to zvu-CHIT ab-STRAKT-no. kak ty E-to iz-ME-rish?', en: "That sounds abstract. How will you measure it?" },
      { speaker: 'Б', ru: 'Через маленькие привычки каждый день.', pr: 'CHE-rez MA-len-ki-ye pri-VYCH-ki KAZH-dy den.', en: 'Through small habits every day.' },
      { speaker: 'А', ru: 'Прогресс важнее совершенства.', pr: 'pro-GRES vazh-NEE so-ver-SHEN-stva.', en: 'Progress is more important than perfection.' },
      { speaker: 'Б', ru: 'Именно. Один шаг вперёд лучше, чем стоять на месте.', pr: 'i-MEN-no. o-DIN shak vper-YOD LUCH-she, chem sto-YAT na MES-te.', en: 'Exactly. One step forward is better than standing still.' },
    ],
  },
  {
    id: 'mindset',
    title: 'Мышление роста',
    en_title: 'Growth Mindset',
    topic: '🧠 Self-Development',
    lines: [
      { speaker: 'А', ru: 'Я боюсь провала. Поэтому не начинаю.', pr: 'ya bo-YUS pro-VA-la. po-E-to-mu ne na-chi-NA-yu.', en: "I'm afraid of failure. That's why I don't start." },
      { speaker: 'Б', ru: 'Провал — это не конец, а обратная связь.', pr: 'pro-VAL — E-to ne ko-NETS, a ob-RAT-na-ya svyaz.', en: 'Failure is not the end — it is feedback.' },
      { speaker: 'А', ru: 'Легко говорить, когда всё получается.', pr: 'lyakh-KO go-vo-RIT, kog-DA vsyo po-lu-CHA-yet-sya.', en: "Easy to say when everything works out." },
      { speaker: 'Б', ru: 'Ошибки — это уроки, замаскированные под проблемы.', pr: 'o-SHIB-ki — E-to u-RO-ki, za-mas-ki-RO-van-ny-ye pod prob-LE-my.', en: 'Mistakes are lessons disguised as problems.' },
      { speaker: 'А', ru: 'Мне нужно изменить отношение к ошибкам.', pr: 'mne NUZH-no iz-me-NIT ot-no-SHE-ni-ye k o-SHIB-kam.', en: 'I need to change my attitude toward mistakes.' },
      { speaker: 'Б', ru: 'Начни с одного: позволь себе не быть идеальным.', pr: 'na-CHNI s od-NO-go: poz-VOL se-BYE ne byt i-de-AL-nym.', en: 'Start with one thing: allow yourself to not be perfect.' },
    ],
  },
  {
    id: 'stress',
    title: 'Сила в трудные времена',
    en_title: 'Strength in Hard Times',
    topic: '💪 Resilience',
    lines: [
      { speaker: 'А', ru: 'У меня сейчас очень тяжёлый период.', pr: 'u men-YA sey-CHAS O-chen tyazh-YO-ly pe-RI-od.', en: "I'm going through a very tough period right now." },
      { speaker: 'Б', ru: 'Расскажи. Иногда просто выговориться — уже помогает.', pr: 'ras-ka-ZHI. i-nog-DA PRO-sto vy-go-vo-RIT-sya — uzhe po-mo-GA-yet.', en: 'Tell me. Sometimes just talking it out already helps.' },
      { speaker: 'А', ru: 'Я чувствую, что не справляюсь.', pr: 'ya CHUST-vu-yu, shto ne sprav-LYA-yus.', en: "I feel like I'm not coping." },
      { speaker: 'Б', ru: 'То, что ты об этом говоришь — уже смелость.', pr: 'to, shto ty ob E-tom go-vo-RISH — UZHE SME-lost.', en: 'The fact that you speak about it is already courage.' },
      { speaker: 'А', ru: 'Как ты остаёшься спокойным в хаосе?', pr: 'kak ty os-ta-YO-shsya spo-KOY-nym v kha-O-se?', en: 'How do you stay calm in chaos?' },
      { speaker: 'Б', ru: 'Я напоминаю себе: это временно. Всё проходит.', pr: 'ya na-po-mi-NA-yu se-BYE: E-to VREM-en-no. vsyo pro-KHO-dit.', en: 'I remind myself: this is temporary. Everything passes.' },
    ],
  },
  {
    id: 'gratitude',
    title: 'Благодарность',
    en_title: 'Gratitude',
    topic: '🙏 Mindfulness',
    lines: [
      { speaker: 'А', ru: 'Ты ведёшь дневник благодарности?', pr: 'ty ve-DYOSH dnyev-NIK bla-go-DAR-nos-ti?', en: 'Do you keep a gratitude journal?' },
      { speaker: 'Б', ru: 'Да. Каждый вечер пишу три вещи, за которые благодарен.', pr: 'da. KAZH-dy VE-cher pi-SHU tri VE-shchi, za ko-TO-ry-ye bla-go-DA-ren.', en: 'Yes. Every evening I write three things I am grateful for.' },
      { speaker: 'А', ru: 'Это реально работает?', pr: 'E-to re-AL-no ra-BO-ta-yet?', en: 'Does it actually work?' },
      { speaker: 'Б', ru: 'Мозг начинает замечать хорошее чаще.', pr: 'mozg na-chi-NA-yet za-me-CHAT kho-RO-she-ye CHA-shche.', en: 'The brain starts noticing the good more often.' },
      { speaker: 'А', ru: 'Даже в плохие дни?', pr: 'DA-zhe v plo-KHI-ye dni?', en: 'Even on bad days?' },
      { speaker: 'Б', ru: 'Особенно в плохие. Это и есть практика.', pr: 'o-SO-ben-no v plo-KHI-ye. E-to i yest PRAK-ti-ka.', en: 'Especially on bad days. That is the practice.' },
    ],
  },
  {
    id: 'presence',
    title: 'Жить настоящим',
    en_title: 'Living in the Present',
    topic: '✨ Mindfulness',
    lines: [
      { speaker: 'А', ru: 'Я постоянно думаю о прошлом или будущем.', pr: 'ya pos-to-YAN-no DU-ma-yu o PROSH-lom i-li bu-DU-shchem.', en: 'I constantly think about the past or the future.' },
      { speaker: 'Б', ru: 'Это ловушка ума. Жизнь происходит только сейчас.', pr: 'E-to lo-VUSH-ka u-MA. zhizn pro-is-KHO-dit TOL-ko sey-CHAS.', en: 'That is a trap of the mind. Life happens only now.' },
      { speaker: 'А', ru: 'Как вернуться в настоящий момент?', pr: 'kak ver-NUT-sya v nas-to-YA-shchy mo-MENT?', en: 'How do you return to the present moment?' },
      { speaker: 'Б', ru: 'Просто почувствуй дыхание. Это якорь.', pr: 'pros-TO po-CHUST-vuy dy-KHA-ni-ye. E-to YA-kor.', en: 'Simply feel your breath. It is an anchor.' },
      { speaker: 'А', ru: 'Такая простая вещь — а работает?', pr: 'ta-KA-ya pros-TA-ya vesh — a ra-BO-ta-yet?', en: 'Such a simple thing — and it works?' },
      { speaker: 'Б', ru: 'Простота и есть его сила.', pr: 'pros-to-TA i yest ye-VO SI-la.', en: 'Simplicity is its strength.' },
    ],
  },
];
