export const STORIES = [
  {
    id: 'morning',
    title: 'Утром без телефона',
    en_title: 'Morning Without the Phone',
    topic: '🌅 Daily Life',
    lines: [
      { speaker: 'А', ru: 'Слушай, ты реально каждое утро так рано встаёшь?', pr: 'SLU-shay, ty re-AL-no KAZH-do-ye UT-ro tak RA-no vsta-YOSH?', en: 'Hey, do you really wake up that early every morning?' },
      { speaker: 'Б', ru: 'Ну да. Сначала казалось — это пытка. А потом привык.', pr: 'nu da. sna-CHA-la ka-ZA-los — E-to PYT-ka. a po-TOM pri-VYK.', en: "Yeah. At first it felt like torture. Then I got used to it." },
      { speaker: 'А', ru: 'Блин. Я в семь уже не человек.', pr: 'blin. ya v sem uzhe ne che-lo-VEK.', en: "Damn. At seven I'm basically not human yet." },
      { speaker: 'Б', ru: 'Да ну. Это просто привычка. Тело само перестраивается.', pr: 'da nu. E-to PROS-to pri-VYCH-ka. TE-lo sa-MO pe-re-STRI-va-yet-sya.', en: 'Come on. It is just habit. The body adjusts on its own.' },
      { speaker: 'А', ru: 'А что делаешь прямо с утра?', pr: 'a shto DE-la-yesh PRYAM-o s UT-ra?', en: 'And what do you do first thing in the morning?' },
      { speaker: 'Б', ru: 'Стакан воды, тишина минут десять — и только потом телефон.', pr: 'sta-KAN vo-DY, ti-SHI-na mi-NUT DE-syat — i TOL-ko po-TOM te-le-FON.', en: 'Glass of water, ten minutes of silence — and only then the phone.' },
      { speaker: 'А', ru: 'Десять минут без телефона — это подвиг, честно.', pr: 'DE-syat mi-NUT bez te-le-FO-na — E-to POD-vig, CHEST-no.', en: "Ten minutes without the phone — honestly, that's heroic." },
      { speaker: 'Б', ru: 'Ха, ну вот в этом и весь смысл.', pr: 'kha, nu vot v E-tom i ves smysl.', en: 'Ha, well — that is exactly the point.' },
    ],
  },
  {
    id: 'burnout',
    title: 'Выгорание',
    en_title: 'Burnout',
    topic: '💆 Mental Health',
    lines: [
      { speaker: 'А', ru: 'Не понимаю, почему я такой уставший. Сплю же нормально.', pr: 'ne po-ni-MA-yu, po-che-MU ya ta-KOY us-TAV-shy. splyu zhe nor-MAL-no.', en: "I don't get why I'm so tired. I sleep fine." },
      { speaker: 'Б', ru: 'Слушай, а ты не думал, что это выгорание?', pr: 'SLU-shay, a ty ne DU-mal, shto E-to vy-go-RA-ni-ye?', en: 'Hey, have you thought that maybe this is burnout?' },
      { speaker: 'А', ru: 'Да ну, я не настолько занят.', pr: 'da nu, ya ne nas-TOL-ko ZA-nyat.', en: "Come on, I'm not that busy." },
      { speaker: 'Б', ru: 'Выгорание — это не про занятость. Это когда внутри пусто.', pr: 'vy-go-RA-ni-ye — E-to ne pro za-NYA-tost. E-to kog-DA vnuf-RI PUS-to.', en: "Burnout is not about being busy. It's when you feel empty inside." },
      { speaker: 'А', ru: 'Честно говоря... да. Прямо вот пусто.', pr: 'CHEST-no go-vo-RYA... da. PRYAM-o vot PUS-to.', en: 'Honestly... yes. Like, genuinely empty.' },
      { speaker: 'Б', ru: 'Тогда это оно. Надо остановиться, пока ещё есть силы.', pr: 'tog-DA E-to o-NO. NA-do os-ta-no-VIT-sya, po-KA ye-SHCHO yest SI-ly.', en: "Then that's it. You need to stop while you still have energy." },
      { speaker: 'А', ru: 'Легко говорить.', pr: 'lyek-KO go-vo-RIT.', en: 'Easy to say.' },
      { speaker: 'Б', ru: 'Начни с одного: один час — только для себя. Без задач.', pr: 'na-CHNI s od-NO-go: o-DIN chas — TOL-ko dlya se-BYA. bez za-DACH.', en: 'Start with one thing: one hour — just for yourself. No tasks.' },
    ],
  },
  {
    id: 'decision',
    title: 'Тяжёлый выбор',
    en_title: 'A Hard Choice',
    topic: '🔀 Life',
    lines: [
      { speaker: 'А', ru: 'Мне предложили работу мечты. Но надо переезжать.', pr: 'mne pred-lo-ZHI-li ra-BO-tu me-CHTYI. no NA-do pe-re-yez-ZHAT.', en: "I've been offered my dream job. But I'd have to move." },
      { speaker: 'Б', ru: 'Ничего себе. И что ты думаешь?', pr: 'ni-che-VO se-BYE. i shto ty DU-ma-yesh?', en: 'Wow. And what are you thinking?' },
      { speaker: 'А', ru: 'Не знаю. Страшно. Тут всё — семья, друзья.', pr: 'ne ZNA-yu. STRASH-no. tut vsyo — sem-YA, druz-YA.', en: "I don't know. It's scary. Everything is here — family, friends." },
      { speaker: 'Б', ru: 'А если не поедешь — потом пожалеешь?', pr: 'a YES-li ne po-YE-desh — po-TOM po-zha-LE-yesh?', en: "And if you don't go — will you regret it later?" },
      { speaker: 'А', ru: 'Вот именно в этом весь ужас.', pr: 'vot I-men-no v E-tom ves U-zhas.', en: "That's exactly the horror of it." },
      { speaker: 'Б', ru: 'Слушай, страх и интуиция — это разные вещи.', pr: 'SLU-shay, strakh i in-tu-I-tsi-ya — E-to RAZ-ny-ye VE-shchi.', en: 'Hey, fear and intuition — those are different things.' },
      { speaker: 'А', ru: 'А как различить?', pr: 'a kak raz-li-CHIT?', en: 'And how do you tell them apart?' },
      { speaker: 'Б', ru: 'Страх говорит «а вдруг». Интуиция говорит «знаю, но боюсь».', pr: 'strakh go-vo-RIT «a vdrug». in-tu-I-tsi-ya go-vo-RIT «ZNA-yu, no bo-YUS».', en: 'Fear says "what if." Intuition says "I know, but I\'m scared."' },
    ],
  },
  {
    id: 'impostor',
    title: 'Синдром самозванца',
    en_title: 'Impostor Syndrome',
    topic: '🧠 Self-Doubt',
    lines: [
      { speaker: 'А', ru: 'Типа, все вокруг такие уверенные, а я чувствую себя самозванцем.', pr: 'TI-pa, vse vok-RUG ta-KI-ye u-VE-ren-ny-ye, a ya CHUST-vu-yu se-BYA sa-mo-ZVAN-tsem.', en: "Like, everyone around seems so confident, and I feel like a fraud." },
      { speaker: 'Б', ru: 'Реально? Ты? Да ты столько всего сделал.', pr: 're-AL-no? ty? da ty STOL-ko vse-VO sde-LAL.', en: "Really? You? But you've done so much." },
      { speaker: 'А', ru: 'Ну и что. Внутри всё равно кажется, что я не тяну.', pr: 'nu i shto. vnuf-RI vsyo rav-NO KA-zhets-ya, shto ya ne tya-NU.', en: "So what. Inside it still feels like I can't handle it." },
      { speaker: 'Б', ru: 'Слушай, это называется синдром самозванца. У большинства умных людей так.', pr: 'SLU-shay, E-to na-zy-VA-yet-sya sin-DROM sa-mo-ZVAN-tsa. u bol-shin-STVA UM-nykh lyu-DEY tak.', en: "Hey, that's called impostor syndrome. Most smart people feel this way." },
      { speaker: 'А', ru: 'Серьёзно?', pr: 'ser-YO-zno?', en: 'Seriously?' },
      { speaker: 'Б', ru: 'Угу. Те, кто реально не тянет — они так не думают. Понял прикол?', pr: 'u-GU. te, kto re-AL-no ne TYA-net — o-NI tak ne DU-ma-yut. PO-nyal pri-KOL?', en: "Yep. People who genuinely can't handle it — they don't think this way. See the irony?" },
      { speaker: 'А', ru: 'Блин. Это... логично.', pr: 'blin. E-to... LO-gich-no.', en: 'Damn. That... makes sense.' },
      { speaker: 'Б', ru: 'Вот именно.', pr: 'vot I-men-no.', en: 'Exactly.' },
    ],
  },
  {
    id: 'phone',
    title: 'Телефон и голова',
    en_title: 'Phone and Your Head',
    topic: '📱 Digital Life',
    lines: [
      { speaker: 'А', ru: 'Короче, заметил — чем больше сижу в телефоне, тем тревожнее.', pr: 'KO-rot-che, za-ME-til — chem BOL-she si-ZHU v te-le-FO-ne, tem tre-VOZH-ne-ye.', en: "So basically, I noticed — the more I scroll, the more anxious I get." },
      { speaker: 'Б', ru: 'Да, это давно доказано. Соцсети — это дофаминовая ловушка.', pr: 'da, E-to dav-NO do-ka-ZA-no. sots-SE-ti — E-to do-fa-MI-no-va-ya lo-VUSH-ka.', en: "Yeah, that's been proven. Social media is a dopamine trap." },
      { speaker: 'А', ru: 'Ладно, но как не сидеть, когда всё там?', pr: 'LAD-no, no kak ne si-DET, kog-DA vsyo tam?', en: "Fine, but how do you not scroll when everything is there?" },
      { speaker: 'Б', ru: 'Я для себя сделал — первый и последний час без телефона.', pr: 'ya dlya se-BYA sde-LAL — PER-vy i pos-LED-ny chas bez te-le-FO-na.', en: "I made a rule for myself — first and last hour without the phone." },
      { speaker: 'А', ru: 'И что, реально помогает?', pr: 'i shto, re-AL-no po-mo-GA-yet?', en: 'And does it actually help?' },
      { speaker: 'Б', ru: 'Реально. Голова яснее, сплю лучше.', pr: 're-AL-no. go-lo-VA YAS-ne-ye, splyu LUCH-she.', en: 'For real. Head is clearer, I sleep better.' },
      { speaker: 'А', ru: 'Надо попробовать. Хотя, честно, звучит как пытка.', pr: 'NA-do po-PRO-bo-vat. kho-TYA, CHEST-no, zvu-CHIT kak PYT-ka.', en: 'Gotta try it. Though honestly it sounds like torture.' },
      { speaker: 'Б', ru: 'Первые три дня — пытка. Потом — кайф.', pr: 'PER-vy-ye tri dnya — PYT-ka. po-TOM — kayf.', en: 'First three days — torture. After that — bliss.' },
    ],
  },
  {
    id: 'meaning',
    title: 'А зачем вообще?',
    en_title: 'What Is the Point?',
    topic: '✨ Purpose',
    lines: [
      { speaker: 'А', ru: 'Слушай, ты когда-нибудь думаешь — а зачем всё это вообще?', pr: 'SLU-shay, ty kog-DA-ni-bud DU-ma-yesh — a za-CHEM vsyo E-to vob-SHCHE?', en: 'Hey, do you ever think — what is the point of all this anyway?' },
      { speaker: 'Б', ru: 'Ха. Ну, это уже философия начинается.', pr: 'kha. nu, E-to uzhe fi-lo-SO-fi-ya na-chi-NA-yet-sya.', en: "Ha. Well, that's where philosophy starts." },
      { speaker: 'А', ru: 'Нет, серьёзно. Вот работаю, устаю... а зачем?', pr: 'net, ser-YO-zno. vot ra-BO-ta-yu, us-ta-YU... a za-CHEM?', en: "No, seriously. I work, I get tired... but why?" },
      { speaker: 'Б', ru: 'Знаешь, я раньше тоже так думал. А потом понял — смысл не находят, его создают.', pr: 'ZNA-yesh, ya RAN-she TO-zhe tak DU-mal. a po-TOM PO-nyal — smysl ne na-KHO-dyat, ye-VO so-zda-YUT.', en: "You know, I used to think that too. Then I realised — meaning is not found, it is created." },
      { speaker: 'А', ru: 'Это как?', pr: 'E-to kak?', en: 'What do you mean?' },
      { speaker: 'Б', ru: 'Ну, ты сам решаешь, что важно. Не общество, не родители — ты.', pr: 'nu, ty sam re-SHA-yesh, shto VAZH-no. ne ob-SHCHE-stvo, ne ro-DI-te-li — ty.', en: "Like, you decide what matters. Not society, not your parents — you." },
      { speaker: 'А', ru: 'А если я пока не знаю, что важно?', pr: 'a YES-li ya po-KA ne ZNA-yu, shto VAZH-no?', en: "And what if I don't know yet what matters?" },
      { speaker: 'Б', ru: 'Вот это и есть начало. Незнание — это не проблема, это старт.', pr: 'vot E-to i yest na-CHA-lo. nez-NA-ni-ye — E-to ne prob-LE-ma, E-to start.', en: 'That is the beginning. Not knowing is not a problem — it is the starting point.' },
    ],
  },
];
